(function(){var h={},mt={},c={id:"7158c55a533ed0cf57dede022b1e6aed",dm:["tech.meituan.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'',ctrk:[],nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,oc:0,aet:'',hca:'E0B9F43837107C08',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,u=!0,v=null,w=!1;mt.cookie={};mt.cookie.set=function(a,b,g){var d;g.N&&(d=new Date,d.setTime(d.getTime()+g.N));document.cookie=a+"="+b+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(d?"; expires="+d.toGMTString():"")+(g.Ic?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:v};
mt.cookie.bc=function(a,b){try{var g="Hm_ck_"+ +new Date;mt.cookie.set(g,"is-cookie-enabled",{domain:a,path:b,N:r});var d="is-cookie-enabled"===mt.cookie.get(g)?"1":"0";mt.cookie.set(g,"",{domain:a,path:b,N:-1});return d}catch(e){return"0"}};mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ua=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.F=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.D=function(a,b){var g=w;if(a==v||!mt.lang.d(a,"Array")||b===r)return g;if(Array.prototype.indexOf)g=-1!==a.indexOf(b);else for(var d=0;d<a.length;d++)if(a[d]===b){g=u;break}return g};mt.url={};mt.url.j=function(a,b){var g=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return g?g[3]:v};
mt.url.Dc=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:v};mt.url.Hb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):v};mt.url.Q=function(a){return(a=mt.url.Hb(a))?a.replace(/:\d+$/,""):a};mt.url.pa=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):v};mt.url.Va=function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)};
mt.url.xa=function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var g=a.indexOf(b);return-1<g&&g+b.length===a.length};
(function(){var a=mt.lang,b=mt.url;mt.g={};mt.g.zb=function(a){return document.getElementById(a)};mt.g.na=function(a){if(!a)return v;try{a=String(a);if(0===a.indexOf("!HMCQ!"))return a;if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var d=a.split(">"),b=document.body,n=d.length-1;0<=n;n--)if(-1<d[n].indexOf("#")){var f=d[n].split("#")[1];(b=document.getElementById(f))||(b=document.getElementById(decodeURIComponent(f)));d=d.splice(n+1,d.length-(n+1));break}for(a=
0;b&&a<d.length;){var l=String(d[a]).toLowerCase();if(!("html"===l||"body"===l)){var n=0,q=d[a].match(/\[(\d+)\]/i),f=[];if(q)n=q[1]-1,l=l.split("[")[0];else if(1!==b.childNodes.length){for(var s=0,t=0,m=b.childNodes.length;t<m;t++){var x=b.childNodes[t];1===x.nodeType&&x.nodeName.toLowerCase()===l&&s++;if(1<s)return v}if(1!==s)return v}for(s=0;s<b.childNodes.length;s++)1===b.childNodes[s].nodeType&&b.childNodes[s].nodeName.toLowerCase()===l&&f.push(b.childNodes[s]);if(!f[n])return v;b=f[n]}a++}return b}catch(k){return v}};
mt.g.pa=function(a,d){var b=[],n=[];if(!a)return n;for(;a.parentNode!=v;){for(var f=0,l=0,q=a.parentNode.childNodes.length,s=0;s<q;s++){var t=a.parentNode.childNodes[s];if(t.nodeName===a.nodeName&&(f++,t===a&&(l=f),0<l&&1<f))break}if((q=""!==a.id)&&d){b.unshift("#"+encodeURIComponent(a.id));break}else q&&(q="#"+encodeURIComponent(a.id),q=0<b.length?q+">"+b.join(">"):q,n.push(q)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+l+"]":""));a=a.parentNode}n.push(b.join(">"));return n};
mt.g.qa=function(a){return(a=mt.g.pa(a,u))&&a.length?String(a[0]):""};mt.g.Kb=function(a){return mt.g.pa(a,w)};mt.g.Ab=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return v};mt.g.Db=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.g.Ib=function(a){var d={top:0,left:0};if(!a)return d;var b=mt.g.Db(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(d=a.getBoundingClientRect());return{top:d.top+(window.pageYOffset||b.scrollTop)-
(b.clientTop||0),left:d.left+(window.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}};mt.g.getAttribute=function(a,d){var b=a.getAttribute&&a.getAttribute(d)||v;if(!b&&a.attributes&&a.attributes.length)for(var n=a.attributes,f=n.length,l=0;l<f;l++)n[l].nodeName===d&&(b=n[l].nodeValue);return b};mt.g.P=function(a){var b="document";a.tagName!==r&&(b=a.tagName);return b.toLowerCase()};mt.g.Ob=function(b){var d="";b.textContent?d=a.trim(b.textContent):b.innerText&&(d=a.trim(b.innerText));d&&(d=d.replace(/\s+/g,
" ").substring(0,255));return d};mt.g.O=function(g,d){var e;a.F(g)&&0===String(g).indexOf("!HMCQ!")?(e=String(g),e=b.j(document.location.href,e.substring(6,e.length))):a.F(g)||(e=mt.g.P(g),"input"===e&&d&&("button"===g.type||"submit"===g.type)?e=a.trim(g.value)||"":"input"===e&&!d&&"password"!==g.type?e=a.trim(g.value)||"":"img"===e?(e=mt.g.getAttribute,e=e(g,"alt")||e(g,"title")||e(g,"src")):e="body"===e||"html"===e?["(hm-default-content-for-",e,")"].join(""):mt.g.Ob(g));return String(e||"").substring(0,
255)};(function(){(mt.g.fc=function(){function a(){if(!a.ba){a.ba=u;for(var b=0,d=n.length;b<d;b++)n[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(b,1);return}a()}var e=w,n=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,w);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!e)if(e=u,"complete"===document.readyState)a.ba=u;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var l=w;try{l=window.frameElement==v}catch(q){}document.documentElement.doScroll&&l&&b()}})();return function(b){a.ba?b():n.push(b)}}()).ba=w})();return mt.g})();mt.event={};
mt.event.e=function(a,b,g){a.attachEvent?a.attachEvent("on"+b,function(b){g.call(a,b)}):a.addEventListener&&a.addEventListener(b,g,w)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=w};
(function(){var a=mt.event;mt.f={};mt.f.Ta=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.f.Cc=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.f.Fc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return w}};mt.f.cookieEnabled=navigator.cookieEnabled;mt.f.javaEnabled=navigator.javaEnabled();
mt.f.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.f.hc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.f.colorDepth=window.screen.colorDepth||0;mt.f.Mb=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.f.Qa=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.f.C=
function(){return mt.f.Mb()+mt.f.Qa()};mt.f.jb=0;mt.f.Qb=function(){var a=document;return parseInt(window.innerWidth||a.documentElement.clientWidth||a.body.offsetWidth||0,10)};mt.f.orientation=0;(function(){function b(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.f.orientation=a;mt.f.jb=mt.f.Qb()}b();a.e(window,"orientationchange",b)})();return mt.f})();mt.G={};
mt.G.parse=function(a){return(new Function("return ("+a+")"))()};
mt.G.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=g[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===v)return"null";if(d instanceof Array){var e=["["],n=d.length,f,l,q;for(l=0;l<n;l++)switch(q=d[l],typeof q){case "undefined":case "function":case "unknown":break;default:f&&e.push(","),e.push(mt.G.stringify(q)),f=1}e.push("]");return e.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+b(d.getMonth()+1)+"-"+b(d.getDate())+"T"+b(d.getHours())+":"+b(d.getMinutes())+":"+b(d.getSeconds())+'"';f=["{"];l=mt.G.stringify;for(n in d)if(Object.prototype.hasOwnProperty.call(d,n))switch(q=
d[n],typeof q){case "undefined":case "unknown":case "function":break;default:e&&f.push(","),e=1,f.push(l(n)+":"+l(q))}f.push("}");return f.join("")}}}();mt.localStorage={};mt.localStorage.ga=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return w}return u};
mt.localStorage.set=function(a,b,g){var d=new Date;d.setTime(d.getTime()+g||31536E6);try{window.localStorage?(b=d.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.ga()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),g=a.substring(0,b)-0;if(g&&g>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.ga())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(d){}return v};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.ga())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(g){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):v}catch(b){return v}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.gb={};mt.gb.log=function(a,b){var g=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=g;g.onload=function(){g.onload=v;g=window[d]=v;b&&b(a)};g.src=a};mt.hb={};
mt.hb.Pb=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return a};
h.A={Ec:"http://tongji.baidu.com/hm-web/welcome/ico",bb:"hm.baidu.com/hm.gif",pb:/^(tongji|hmcdn).baidu.com$/,tc:"tongji.baidu.com",Ub:"hmmd",Vb:"hmpl",wc:"utm_medium",Tb:"hmkw",yc:"utm_term",Rb:"hmci",vc:"utm_content",Wb:"hmsr",xc:"utm_source",Sb:"hmcu",uc:"utm_campaign",M:0,J:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ya:"https:",Gc:0,Ac:6E5,Hc:6E5,ic:5E3,Bc:5,Na:1024,zc:1,Aa:2147483647,ib:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt ua".split(" "),
R:u,Ka:["a","input","button"],Ha:{id:"data-hm-id",W:"data-hm-class",V:"data-hm-xpath",content:"data-hm-content",da:"data-hm-tag",link:"data-hm-link"},Ja:"data-hm-enabled",Ia:"data-hm-disabled",ec:"https://hmcdn.baidu.com/static/tongji/plugins/",ab:["UrlChangeTracker","OcpcCbHm"]};(function(){var a={B:{},e:function(a,g){this.B[a]=this.B[a]||[];this.B[a].push(g)},K:function(a,g){this.B[a]=this.B[a]||[];for(var d=this.B[a].length,e=0;e<d;e++)this.B[a][e](g)}};return h.t=a})();
(function(){var a=mt.lang,b=/^https?:\/\//,g={Cb:function(a){var b;try{b=JSON.parse(decodeURIComponent(a[0]))}catch(n){}return b},Wa:function(a,b){return g.Xa(h.c&&h.c.b&&h.c.b.u,a,b)||g.Xa(document.location.href,a,b)},Xa:function(a,e,n){if(a===r)return w;b.test(e)||(a=a.replace(b,""));e=e.replace(/\/$/,"");a=a.replace(/\/$/,"");n&&(a=a.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+e.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(a)},Z:function(b,e){var n=g.Cb(b);if(!a.d(n,
"Undefined")){if(a.d(n,"Array")){for(var f=0;f<n.length;f++)if(g.Wa(n[f],e))return u;return w}if(a.d(n,"Object")){var f=[],l;for(l in n)n.hasOwnProperty(l)&&g.Wa(l,e)&&(f=f.concat(n[l]));return f}}}};return h.ka=g})();
(function(){function a(a,d){var e=document.createElement("script");e.charset="utf-8";b.d(d,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=v,d()}:e.onload=function(){d()});e.src=a;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)}var b=mt.lang;return h.load=a})();
(function(){var a=mt.url,b=mt.cookie,g=mt.localStorage,d=mt.sessionStorage,e={getData:function(a){try{return b.get(a)||d.get(a)||g.get(a)}catch(f){}},setData:function(a,f,l){try{b.set(a,f,{domain:e.$(),path:e.ma(),N:l}),l?g.set(a,f,l):d.set(a,f)}catch(q){}},removeData:function(a){try{b.set(a,"",{domain:e.$(),path:e.ma(),N:-1}),d.remove(a),g.remove(a)}catch(f){}},$:function(){for(var b=document.location.hostname,d=0,e=c.dm.length;d<e;d++)if(a.xa(b,c.dm[d]))return c.dm[d].replace(/(:\d+)?[/?#].*/,"");
return b},ma:function(){for(var b=0,d=c.dm.length;b<d;b++){var e=c.dm[b];if(-1<e.indexOf("/")&&a.Va(document.location.href,e))return e.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.X=e})();
(function(){var a=mt.lang,b=mt.G,g=h.X,d={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},e={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},n=["session","user"],f="Hm_up_"+c.id,l={init:function(){l.Zb()},Zb:function(){try{var e=b.parse(decodeURIComponent(g.getData(f)));a.d(e,"Object")&&(d.user=e)}catch(s){}},s:function(a){var b={};d[a]!==r&&(b=d[a]);a=this.ra();for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a},ra:function(){for(var a={},b,e=n.length-
1;0<=e;e--){b=d[n[e]];for(var m in b)b.hasOwnProperty(m)&&(a[m]=b[m])}return a},setProperty:function(e,f,g){var m=d[e];if(a.d(m,"Object")&&a.d(f,"Object")){for(var x in f)if(f.hasOwnProperty(x)){var k=a.h(String(x));if(g||!/^_/.test(k)&&!/_$/.test(k)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(k)){var p=f[x];if(p==v)delete m[k];else{if(a.d(p,"Object")||a.d(p,"Array"))p=b.stringify(p);p=a.h(String(p));l.ac(e,k,p)&&(m[k]={value:p,scope:l.Pa(e)})}}}"user"===e&&l.Ca()}},n:function(b){b!==r&&("userId"===
b&&a.d(d.user,"Object")?(delete d.user.uid_,l.Ca()):"user"===b&&a.d(d.user,"Object")?(b=d.user.uid_,d.user=b===r?{}:{uid_:b},l.Ca()):d[b]!==r&&(d[b]={}))},Ca:function(){try{g.setData(f,encodeURIComponent(b.stringify(d.user)),c.age)}catch(a){}},ac:function(a,b,e){var m=u,f=d[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(e)).length)m=w;else{var k=f[b];f[b]={value:e,scope:l.Pa(a)};a=l.I(l.s(a));2048<encodeURIComponent(a).length&&(k!==r?f[b]=k:delete f[b],m=w)}return m},
I:function(a){var b=[],d,m;for(m in a)a.hasOwnProperty(m)&&(d=[m,a[m].value],(1===a[m].scope||2===a[m].scope)&&d.push(a[m].scope),b.push(d.join("*")));return b.join("!")},Pa:function(a){a=e[a];return a!==r?a:e.others}};return h.L=l})();
(function(){var a=mt.g,b=mt.lang,g=h.t,d=h.ka,e=h.L,n=e.I;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var f={$a:{},ea:{},init:function(){for(var a,e=d.Z(c.cptrk)||[],g=0;g<e.length;g++)if(a=e[g],a.a!==r&&b.d(a.a,"Object")){a=a.a;for(var n in a)a.hasOwnProperty(n)&&(f.ea[n]=String(a[n]))}},Za:function(){var b,d,e;for(e in f.ea)if(f.ea.hasOwnProperty(e)&&f.$a[e]===r&&(b=f.ea[e],b=a.na(b)))d=d===r?{}:d,d[e]=a.O(b,w),f.$a[e]=u;return d},ta:function(){var a=f.Za();a&&f.kc(a)},Yb:function(){"MutationObserver"in
window&&document.body?(new MutationObserver(f.ta)).observe(document.body,{childList:u,subtree:u}):window.setInterval(f.ta,15E3)},kc:function(a){if(b.d(a,"Object")){e.setProperty("pageview",a);a=h.c.b.p;var d=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=n(e.s("pageview"));h.c.m();h.c.b.p=a;h.c.b.ep=d;e.n("pageview")}}};f.init();g.e("pv-b",function(){var a=f.Za();a&&e.setProperty("pageview",a)});f.Yb();a.fc(f.ta)}})();
(function(){var a=mt.lang,b=mt.g,g=h.ka,d={Y:function(a,n){return function(f){var l=f.target||f.srcElement;if(l){var q=g.Z(n)||[],s=l.getAttribute(a.fa);f=f.clientX+":"+f.clientY;if(s&&s===f)l.removeAttribute(a.fa);else if(0<q.length&&(l=b.Kb(l))&&l.length)if(q=l.length,s=l[l.length-1],1E4>q*s.split(">").length)for(s=0;s<q;s++)d.fb(a,l[s]);else d.fb(a,s)}}},fb:function(b,d){for(var f={},g=String(d).split(">").length,q=0;q<g;q++)f[d]="",d=d.substring(0,d.lastIndexOf(">"));b&&(a.d(b,"Object")&&b.La)&&
b.La(f)},gc:function(a,b){return function(d){(d.target||d.srcElement).setAttribute(a.fa,d.clientX+":"+d.clientY);a&&a.o&&(b?a.o(b):a.o("#"+encodeURIComponent(this.id),d.type))}}};return h.vb=d})();
(function(){var a=mt.g,b=mt.event,g=mt.lang,d=h.A,e=h.ka,n=h.vb,f=h.L,l=f.I,q={fa:"HM_ce",lb:function(){if(c.cetrk&&0<c.cetrk.length){b.e(document,"click",n.Y(q,c.cetrk));for(var d=e.Z(c.cetrk)||[],f=0,m=d.length;f<m;f++){var g=d[f],k=g.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=a.zb(k))&&b.e(k,"click",n.gc(q,g)))}}},La:function(a){for(var b=e.Z(c.cetrk)||[],d=0;d<b.length;d++){var f=b[d],k=q.Fb(f.p,a);k&&q.o(f,k)}},Fb:function(a,b){a=String(a);if(0<a.indexOf("*")){var d=
RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),e;for(e in b)if(b.hasOwnProperty(e)&&d.test(e))return e;return v}return b.hasOwnProperty(a)?a:v},o:function(b,d){h.c.b.et=7;var e=b&&b.k||"",e=g.h(e),x={};if(b&&b.a&&g.d(b.a,"Object")){var k=b.a,p;for(p in k)if(k.hasOwnProperty(p)){var y=q.Lb(k[p]||"",d),y=y?a.O(y,w):"";x[p]=y}}x=q.Bb(x,d||b&&b.p);x._iden=e;f.setProperty("customEvent",x);h.c.b.ep="";h.c.b.p=l(f.s("customEvent"));h.c.m();h.c.b.p="";f.n("customEvent")},
Bb:function(b,e){var m=a.na(e),f=d.Ha;m&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(m,f.id)||a.getAttribute(m,"id")||"",b.ec_=a.getAttribute(m,f.W)||a.getAttribute(m,"class")||"",b.ex_=a.getAttribute(m,f.V)||a.qa(m),b.en_=a.getAttribute(m,f.content)||a.O(m,u),b.et_=a.getAttribute(m,f.da)||a.P(m),b.el_=a.getAttribute(m,f.link)||a.getAttribute(m,"href")||""):(b.ex_=a.getAttribute(m,f.V)||a.qa(m),b.en_=a.getAttribute(m,f.content)||a.O(m,u)));return b},Lb:function(b,d){b=String(b);d=String(d);if(0<b.indexOf("*")){var e=
/.*\[(\d+)\]$/.exec(d);b=b.replace("*",e?e[1]:"1")}return a.na(b)}};h.t.e("pv-b",q.lb);return q})();
(function(){var a=mt.lang,b=mt.g,g=mt.event,d=mt.f,e=h.A,n=h.t,f=h.L,l=f.I,q=+new Date,s=[],t={Y:function(){return function(d){if(h.c&&h.c.R&&c.aet&&c.aet.length){var f=d.target||d.srcElement;if(f){var k=h.c.Ka,p=b.getAttribute(f,e.Ja)!=v?u:w;if(b.getAttribute(f,e.Ia)==v)if(p)t.ha(t.oa(f,d));else{var g=b.P(f);if(a.D(k,"*")||a.D(k,g))t.ha(t.oa(f,d));else for(;f.parentNode!=v;){var p=f.parentNode,g=b.P(p),z="a"===g&&a.D(k,"a")?u:w,g="button"===g&&a.D(k,"button")?u:w,A=b.getAttribute(p,e.Ja)!=v?u:w;
if(b.getAttribute(p,e.Ia)==v&&(z||g||A)){t.ha(t.oa(p,d));break}f=f.parentNode}}}}}},oa:function(f,g){var k={},p=e.Ha;k.id=b.getAttribute(f,p.id)||b.getAttribute(f,"id")||"";k.W=b.getAttribute(f,p.W)||b.getAttribute(f,"class")||"";k.V=b.getAttribute(f,p.V)||b.qa(f);k.content=b.getAttribute(f,p.content)||b.O(f,u);k.da=b.getAttribute(f,p.da)||b.P(f);k.link=b.getAttribute(f,p.link)||b.getAttribute(f,"href")||"";k.type=g.type||"click";p=a.Ua(f.offsetTop)?f.offsetTop:0;"click"===g.type?p=d.Ta?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.Ya&&g.Ya.changedTouches)&&(p=g.Ya.changedTouches[0].pageY);k.sc=p;p=this.Eb(g);k.za=p.za||0;k.Ba=p.Ba||0;k.Ga=p.Ga||0;k.sa=p.sa||0;k.Ea=p.Ea||"b";return k},Eb:function(f){var e=f.target||f.srcElement,k;if(d.Ta){var p=Math.max(document.documentElement.scrollTop,document.body.scrollTop);k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);k=f.clientX+k;f=f.clientY+p}else k=f.pageX,
f=f.pageY;var g=p=0,z=0,A=0;if(e&&(p=e.offsetWidth||e.clientWidth,g=e.offsetHeight||e.clientHeight,A=b.Ib(e),z=A.left,A=A.top,a.d(e.getBBox,"Function")&&(g=e.getBBox(),p=g.width,g=g.height),"html"===(e.tagName||"").toLowerCase()))p=Math.max(p,e.clientWidth),g=Math.max(g,e.clientHeight);return{za:Math.round(100*((k-z)/p)),Ba:Math.round(100*((f-A)/g)),Ga:p,sa:g,Ea:("a"===(e.tagName||"").toLowerCase()?e:b.Ab(e))?"a":"b"}},ha:function(b){var d=a.h;b=[+new Date-(h.c.S!==r?h.c.S:q),d(b.id),d(b.W),d(b.da),
d(b.V),d(b.link),d(b.content),b.type,b.sc,b.za,b.Ba,b.Ga,b.sa,b.Ea].join("*");t.ia(b);a.d(this.U(),"Function")&&this.U()()},ia:function(a){var b=e.Na;a.length>b||(encodeURIComponent(s.join("!")+a).length>b&&0<s.length&&(t.o(s.join("!")),s=[]),s.push(a))},o:function(a){h.c.b.et=5;h.c.b.ep=a;f.setProperty("autoEventTracking",{view_h_:d.C()},u);h.c.b.p=l(f.s("autoEventTracking"));h.c.m();h.c.b.p="";f.setProperty("autoEventTracking",{view_h_:v},u)},U:function(){return function(){s&&s.length&&(t.o(s.join("!")),
s=[])}}};a.F(c.aet)&&""!==c.aet&&n.e("pv-b",function(){g.e(document,"click",t.Y());"ontouchend"in document&&g.e(window,"touchend",t.Y());g.e(window,"unload",t.U())});return t})();
(function(){var a=mt.lang,b=mt.event,g=mt.f,d=h.A,e=h.t,n=h.L,f=n.I,l=+new Date,q=[],s=v,t={nb:function(){a.F(c.aet)&&""!==c.aet&&setInterval(t.eb,d.ic)},eb:function(){var a=g.C();0<a-h.c.b.vl&&(h.c.b.vl=a)}},m={ub:function(){return function(){h.c&&(h.c.R&&c.aet&&c.aet.length)&&(window.clearTimeout(s),s=window.setTimeout(function(){m.mb(g.C())},150))}},mb:function(a){m.ia([+new Date-(h.c.S!==r?h.c.S:l),a].join("*"))},ia:function(a){if(encodeURIComponent(q.join("!")+a).length>d.Na||3<q.length)m.o(q.join("!")),
q=[];q.push(a)},o:function(a){t.eb();h.c.b.et=6;h.c.b.vh=g.Qa();h.c.b.ep=a;n.setProperty("autoEventTracking",{view_h_:g.C()},u);h.c.b.p=f(n.s("autoEventTracking"));h.c.m();h.c.b.p="";n.setProperty("autoEventTracking",{view_h_:v},u)},U:function(){return function(){q&&q.length&&(m.o(q.join("!")),q=[])}}};a.F(c.aet)&&""!==c.aet&&e.e("pv-b",function(){b.e(window,"scroll",m.ub());b.e(window,"unload",m.U());t.nb()});return m})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.la.Jb()+","+h.la.Gb();h.c.b.hca=c.hca;h.c.m()}}function b(){clearTimeout(z);var a;p&&(a="visible"==document[p]);y&&(a=!document[y]);l="undefined"==typeof a?u:a;if((!f||!q)&&l&&s)k=u,m=+new Date;else if(f&&q&&(!l||!s))k=w,x+=+new Date-m;f=l;q=s;z=setTimeout(b,100)}function g(a){var b=document,p="";if(a in b)p=a;else for(var d=["webkit","ms","moz","o"],f=0;f<d.length;f++){var e=d[f]+a.charAt(0).toUpperCase()+a.slice(1);
if(e in b){p=e;break}}return p}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))s="focus"==a.type||"focusin"==a.type?u:w,b()}var e=mt.event,n=h.t,f=u,l=u,q=u,s=u,t=+new Date,m=t,x=0,k=u,p=g("visibilityState"),y=g("hidden"),z;b();(function(){var a=p.replace(/[vV]isibilityState/,"visibilitychange");e.e(document,a,b);e.e(window,"pageshow",b);e.e(window,"pagehide",b);"object"==typeof document.onfocusin?(e.e(document,"focusin",d),e.e(document,"focusout",d)):(e.e(window,
"focus",d),e.e(window,"blur",d))})();h.la={Jb:function(){return+new Date-t},Gb:function(){return k?+new Date-m+x:x}};n.e("pv-b",function(){e.e(window,"unload",a())});n.e("duration-send",a());n.e("duration-done",function(){m=t=+new Date;x=0});return h.la})();
(function(){var a=mt.lang,b=h.A,g=h.load,d=h.X,e={Xb:function(e){if((window._dxt===r||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var f=d.$();g([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(f)].join(""),e)}},rc:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.sb=e})();
(function(){function a(a,b,d,f){if(!(a===r||b===r||f===r)){if(""===a)return[b,d,f].join("*");a=String(a).split("!");for(var e,k=w,g=0;g<a.length;g++)if(e=a[g].split("*"),String(b)===e[0]){e[1]=d;e[2]=f;a[g]=e.join("*");k=u;break}k||a.push([b,d,f].join("*"));return a.join("!")}}function b(a){for(var f in a)if({}.hasOwnProperty.call(a,f)){var e=a[f];d.d(e,"Object")||d.d(e,"Array")?b(e):a[f]=String(e)}}var g=mt.url,d=mt.lang,e=mt.G,n=mt.f,f=h.A,l=h.t,q=h.sb,s=h.load,t=h.X,m=h.L,x=m.I,k={T:[],ca:0,wa:w,
z:{Fa:"",page:""},init:function(){k.i=0;m.init();l.e("pv-b",function(){k.tb();k.wb()});l.e("pv-d",function(){k.xb();k.z.page=""});l.e("stag-b",function(){h.c.b.api=k.i||k.ca?k.i+"_"+k.ca:"";h.c.b.ct=[decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),k.z.Fa,k.z.page].join("!")});l.e("stag-d",function(){h.c.b.api=0;k.i=0;k.ca=0})},tb:function(){var a=window._hmt||[];if(!a||d.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var p=arguments[b];
d.d(p,"Array")&&(a.cmd[a.id].push(p),"_setAccount"===p[0]&&(1<p.length&&/^[0-9a-f]{31,32}$/.test(p[1]))&&(p=p[1],a.id=p,a.cmd[p]=a.cmd[p]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},wb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order)$/,f=0,e=b.length;f<e;f++){var g=b[f];d.test(g[0])?k.T.push(g):k.Da(g)}a.cmd[c.id]={push:k.Da}},xb:function(){if(0<k.T.length)for(var a=0,b=k.T.length;a<b;a++)k.Da(k.T[a]);k.T=v},Da:function(a){var b=
a[0];if(k.hasOwnProperty(b)&&d.d(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{31,32}$/.test(a[1])&&(k.i|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||u===a))k.i|=2,h.c.Ra=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(k.i|=4,h.c.b.sn=h.c.Oa(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=n.C(),h.c.b.kb=0,h.c.va?(h.c.b.nv=0,h.c.b.st=4):h.c.va=u,k.wa||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=f.protocol+"//"+document.location.host+
a[1],h.c.b.p=x(m.s("pageview")),h.c.m(),h.c.b.p="",h.c.S=+new Date,m.n("pageview"))},_trackEvent:function(a){2<a.length&&(k.i|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.h(a[1])+"*"+d.h(a[2])+(a[3]?"*"+d.h(a[3]):"")+(a[4]?"*"+d.h(a[4]):""),h.c.b.p=x(m.ra()),h.c.m(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],f=a[4]||3;if(0<b&&6>b&&0<f&&4>f){k.ca++;for(var e=(h.c.b.cv||"*").split("!"),g=e.length;g<b-1;g++)e.push("*");e[b-1]=f+"*"+d.h(a[2])+"*"+d.h(a[3]);h.c.b.cv=e.join("!");
a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?t.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):t.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var f=d.h(b[1]);b=d.h(b[2]);if(f!==r&&b!==r){var e=decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),e=a(e,f,1,b);t.setData("Hm_ct_"+c.id,encodeURIComponent(e),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var f=d.h(b[1]);b=d.h(b[2]);if(f!==r&&b!==r){var e=k.z.Fa,e=a(e,f,2,b);k.z.Fa=e}}},_setPageTag:function(b){if(!(3>
b.length)){var e=d.h(b[1]);b=d.h(b[2]);if(e!==r&&b!==r){var f=k.z.page,f=a(f,e,3,b);k.z.page=f}}},_setReferrerOverride:function(a){1<a.length&&(a=a[1],d.d(a,"String")?(h.c.b.su="/"===a.charAt(0)?f.protocol+"//"+window.location.host+a:a,k.wa=u):k.wa=w)},_trackOrder:function(a){a=a[1];d.d(a,"Object")&&(b(a),k.i|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=e.stringify(a),h.c.b.p=x(m.ra()),h.c.m(),h.c.b.p="")},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.i|=
32,h.c.b.et=93,h.c.b.ep=a,h.c.m()},_setDataxId:function(a){a=a[1];q.Xb();q.rc(a)},_setUserId:function(a){a=a[1];if(a!==r&&(d.F(a)||d.Ua(a))){var b=m.s("user").uid_;if(!(b&&b.value===d.h(String(a)))){var b=h.c.b.p,f=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+d.h(String(a));h.c.m();var e={};e.uid_=a;m.setProperty("user",e,u);h.c.b.p=b;h.c.b.ep=f}}},_clearUserId:function(a){1<a.length&&u===a[1]&&m.n("userId")},_setUserProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("user",a)},_clearUserProperty:function(a){1<
a.length&&u===a[1]&&m.n("user")},_setSessionProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&u===a[1]&&m.n("session")},_setPageviewProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&u===a[1]&&m.n("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];d.d(a,"Object")&&m.setProperty("autoEventTracking",a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&
u===a[1]&&m.n("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.Sa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.R=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.m())):l.K("duration-send");l.K("duration-done")},_require:function(a){1<a.length&&(a=a[1],f.pb.test(g.Q(a))&&s(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1];a=a[2];if(d.D(f.ab,
e)&&d.d(a,"Function")&&(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[e]=a,b.w=b.w||[],a=b.w.slice(),e&&a.length&&a[0][1]===e))for(var g=0,k=a.length;g<k;g++){var l=a[g][2]||{};if(b.plugins[e]&&!b.H[e])b.H[e]=new b.plugins[e](l),b.w.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],g=a[2]||{};if(d.D(f.ab,e))if(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[e]&&!b.H[e])b.H[e]=new b.plugins[e](g);else{b.w=b.w||[];for(var g=0,l=b.w.length;g<l;g++)if(b.w[g][1]===
e)return;b.w.push(a);k._require([v,f.ec+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];d.d(a,"Object")||(a={});a._iden=b;m.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=x(m.s("customEvent"));h.c.m();h.c.b.p="";m.n("customEvent")}}};k.init();h.qb=k;return h.qb})();
(function(){var a=h.t;c.spa!==r&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.b={},this.Sa=this.Ra=u,this.R=k.R,this.Ka=e.F(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.va=w,this.init())}var b=mt.url,g=mt.gb,d=mt.hb,e=mt.lang,n=mt.cookie,f=mt.f,l=mt.sessionStorage,q=mt.G,s=mt.event,t=h.X,m=h.L,x=m.I,k=h.A,p=h.load,y=h.t;a.prototype={aa:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(b.Va(a,c.dm[d]))return u}else{var e=b.Q(a);if(e&&b.xa(e,
c.dm[d]))return u}return w},Nb:function(){if(!document.referrer)return k.J-k.M>c.vdur?1:4;var a=w;this.aa(document.referrer)&&this.aa(document.location.href)?a=u:(a=b.Q(document.referrer),a=b.xa(a||"",document.location.hostname));return a?k.J-k.M>c.vdur?1:4:3},nc:function(){var a,b,d,e,f,g;k.M=t.getData("Hm_lpvt_"+c.id)||0;13===k.M.length&&(k.M=Math.round(k.M/1E3));b=this.Nb();a=4!==b?1:0;if(g=t.getData("Hm_lvt_"+c.id)){e=g.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.J-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.J);4<e.length;)e.shift();g=e.join(",");e=e[e.length-1]}else g=k.J,e="",f=1;this.$b()?(t.setData("Hm_lvt_"+c.id,g,c.age),t.setData("Hm_lpvt_"+c.id,k.J),d=n.bc(t.$(),t.ma())):this.yb();if(0===c.nv&&this.aa(document.location.href)&&(""===document.referrer||this.aa(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},qc:function(){var a=[];try{var b=this;if("userAgentData"in navigator){for(var e=
navigator.userAgentData,d=e.brands,f=[],g=0;g<d.length;g++)f.push([d[g]&&d[g].brand?d[g].brand:"",d[g]&&d[g].version?d[g].version:""].join(";"));a.push(f.join(","));a.push(e.mobile);e.getHighEntropyValues(["platform","platformVersion","architecture","model","uaFullVersion"]).then(function(d){a.push(d.platform);a.push(d.platformVersion);a.push(d.architecture);a.push(d.model);a.push(d.uaFullVersion);b.b.ua=a.join("!")})}}catch(k){}},$b:function(){var a=b.Q(document.location.href);return!e.D("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},yb:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&t.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&t.removeData(d[0])}},mc:function(){for(var a=[],b=this.b.et,d=0,e=k.ib.length;d<e;d++){var f=k.ib[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},pc:function(){this.nc();
this.qc();this.b.si=c.id;this.b.sn=this.Oa();this.b.su=document.referrer;this.b.ds=f.hc;this.b.cl=f.colorDepth+"-bit";this.b.ln=String(f.language).toLowerCase();this.b.ja=f.javaEnabled?1:0;this.b.ck=f.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=d.Pb();this.b.v="1.2.71";this.b.cv=decodeURIComponent(t.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=f.C();var a=document.location.href;this.b.cm=b.j(a,k.Ub)||"";this.b.cp=b.j(a,k.Vb)||b.j(a,k.wc)||"";this.b.cw=
b.j(a,k.Tb)||b.j(a,k.yc)||"";this.b.ci=b.j(a,k.Rb)||b.j(a,k.vc)||"";this.b.cf=b.j(a,k.Wb)||b.j(a,k.xc)||"";this.b.cu=b.j(a,k.Sb)||b.j(a,k.uc)||"";/https?:/.test(document.location.protocol)&&(this.b.u=a)},init:function(){try{this.pc(),0===this.b.nv?this.lc():this.Ma(),h.c=this,this.rb(),this.dc(),y.K("pv-b"),this.jc()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));g.log(k.ya+
"//"+k.bb+"?"+b.join("&"))}},jc:function(){function a(){y.K("pv-d")}this.Ra?(this.va=u,this.b.et=0,this.b.ep="",this.b.p=x(m.s("pageview")),this.b.vl=f.C(),this.m(a),this.b.p=""):a();this.S=+new Date;m.n("pageview")},m:function(a){if(this.Sa){var b=this;b.b.rnd=Math.round(Math.random()*k.Aa);b.b.r=f.orientation;b.b.ww=f.jb;y.K("stag-b");var d=k.ya+"//"+k.bb+"?"+b.mc();y.K("stag-d");b.ob(d);g.log(d,function(d){b.cb(d);e.d(a,"Function")&&a.call(b)})}},rb:function(){try{if(window.postMessage&&window.self!==
window.parent){var a=this;s.e(window,"message",function(d){if(b.Q(d.origin)===k.tc){d=d.data||{};var e=d.jn||"",f=/^customevent$|^heatmap$|^pageclick$|^select$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*k.Aa),p(k.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(d){}},dc:function(){try{if(window.self===window.parent){var a=document.location.href,d=b.j(a,"baidu-analytics-token"),
e=b.j(a,"baidu-analytics-jn");/^[a-f0-9]{32}\/?$/.test(d)&&/^overlay\/?$/.test(e)&&p(k.protocol+"//"+c.js+e+".js?"+Math.round(Math.random()*k.Aa))}}catch(f){}},ob:function(a){var b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+c.id,q.stringify(b))},cb:function(a){var b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,
"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,q.stringify(b)):this.Ma()}},Ma:function(){l.remove("Hm_unsent_"+c.id)},lc:function(){var a=this,b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var e=function(b){g.log(k.ya+"//"+b,function(b){a.cb(b)})},f=0;f<b.length;f++)e(b[f])},Oa:function(){return Math.round(+new Date/1E3)%65535}};return new a})();var B=h.A,C=h.load;
c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));})();
